name: aws-cli
summary: Universal Command Line Interface for Amazon Web Services
description: |
 This package provides a unified command line interface to Amazon Web
 Services.
version: git
base: core18
adopt-info: aws
confinement: strict
grade: stable

plugs:
  personal-files:
    write:
      - $HOME/.aws

apps:
  aws:
    adapter: full
    command-chain:
      - bin/launcher.sh
    command: bin/aws
    completer: bin/aws_bash_completer
    plugs:
      - network
      - network-bind
      - personal-files
      - home

parts:
  launcher:
    plugin: dump
    source: https://github.com/mikf/gallery-dl.git
    source-depth: 1
    organize:
      snap/local/launchers/gallery-dl-launch: bin/launcher.sh
    prime:
      - bin/launcher.sh
  aws:
    plugin: python
    source: https://github.com/aws/aws-cli.git
    override-build: |
      git describe --tags $(git rev-list --tags --max-count=1) > $SNAPCRAFT_STAGE/version
      TAG=$(cat $SNAPCRAFT_STAGE/version)
      git checkout tags/$TAG
      snapcraftctl build
      snapcraftctl set-version $TAG
    stage-packages:
      - groff-base  # for `aws help`
